- name: Configuration of build node
  hosts: ec2_build
  user: ubuntu
  gather_facts: true

  tasks:
  - name: Esure git and maven package is present
    become: true
    apt:
      update_cache: yes
      name:
      - git
      - maven
      - python3-pip
      state: present

  - name: Installing boto3
    shell: pip3 install --upgrade boto3

  - name: Clone repository
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /tmp/boxfuse-sample-java-war-hello

  - name: Build war
    shell: mvn -f /tmp/boxfuse-sample-java-war-hello package

  - name: Ensure that artifact copied to S3 bucket
    aws_s3:
      bucket: bucket4artifacts
      object: hello-1.0.war
      src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
      mode: put


  
- name: production
  hosts: prod
  become: yes

  tasks:
  - name: Ensure tomcat package is present
    apt:
      name: tomcat9
      state: present

  # Synchronization of src on the deligate host to the dest on the inventory host in pull mode
  - name:  Implement of transfer artifact to prodaction server
    aws_s3:
      bucket: bucket4artifacts
      object: hello-1.0.war
      dest: /var/lib/tomcat9/webapps/hello-1.0.war
      mode: get

  - name: Ensure tomcat service is started
    service:
     name: tomcat9
     state: started